# Generated by Django 4.2.5 on 2023-10-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applipizza', '0002_composition'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='image',
            field=models.ImageField(default='imagesPizzas/default.PNG', upload_to='imagesPizzas/'),
        ),
    ]
