# Generated by Django 4.2.7 on 2023-11-12 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applicompte', '0002_alter_pizzauser_image'),
        ('applipizza', '0003_pizza_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('idCommande', models.AutoField(primary_key=True, serialize=False)),
                ('dateCommande', models.DateField(verbose_name='date de passage de la commande')),
                ('payee', models.BooleanField(verbose_name='commande payee ?')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='prix total')),
                ('pizzauser_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicompte.pizzauser')),
            ],
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('idLigneCommande', models.AutoField(primary_key=True, serialize=False)),
                ('quantite', models.IntegerField(verbose_name='nombre de pizza(s)')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='prix total')),
                ('commande_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applipanier.commande')),
                ('pizza_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applipizza.pizza')),
            ],
            options={
                'unique_together': {('commande_id', 'pizza_id')},
            },
        ),
    ]
