# Generated by Django 4.2.7 on 2023-11-12 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applipanier', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='pizzauser_id',
            new_name='pizzauser',
        ),
        migrations.RenameField(
            model_name='lignecommande',
            old_name='commande_id',
            new_name='commande',
        ),
        migrations.RenameField(
            model_name='lignecommande',
            old_name='pizza_id',
            new_name='pizza',
        ),
    ]
