# Generated by Django 4.2.7 on 2023-11-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicompte', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzauser',
            name='image',
            field=models.ImageField(default='imagesUsers/default.png', upload_to='imagesUsers/'),
        ),
    ]
